"""empty message

Revision ID: 16accaa63a27
Revises: c1a2f6174b5a
Create Date: 2019-11-08 21:40:20.455812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16accaa63a27'
down_revision = 'c1a2f6174b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'note', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    # ### end Alembic commands ###
