"""empty message

Revision ID: 1bab4c378730
Revises: 279e0ab5a1ad
Create Date: 2019-11-10 10:18:35.469836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bab4c378730'
down_revision = '279e0ab5a1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time_zone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time_zone')
    # ### end Alembic commands ###
