"""note table

Revision ID: 24a0b10ebb92
Revises: 3af90d45683e
Create Date: 2019-11-08 16:06:51.296094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a0b10ebb92'
down_revision = '3af90d45683e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('note_date', sa.DateTime(), nullable=True),
    sa.Column('last_edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_last_edited'), 'note', ['last_edited'], unique=False)
    op.create_index(op.f('ix_note_note'), 'note', ['note'], unique=False)
    op.create_index(op.f('ix_note_note_date'), 'note', ['note_date'], unique=False)
    op.create_index(op.f('ix_note_title'), 'note', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_title'), table_name='note')
    op.drop_index(op.f('ix_note_note_date'), table_name='note')
    op.drop_index(op.f('ix_note_note'), table_name='note')
    op.drop_index(op.f('ix_note_last_edited'), table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###
