"""users table

Revision ID: 3af90d45683e
Revises: e4b79529c734
Create Date: 2019-11-08 15:48:01.645429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af90d45683e'
down_revision = 'e4b79529c734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_creation_date'), 'user', ['creation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_creation_date'), table_name='user')
    # ### end Alembic commands ###
