"""empty message

Revision ID: 74ad07cafa64
Revises: 
Create Date: 2019-11-26 13:41:55.691185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ad07cafa64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_tag'), 'tag', ['tag'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('time_zone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_creation_date'), 'user', ['creation_date'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('note_date', sa.DateTime(), nullable=True),
    sa.Column('last_edited', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_last_edited'), 'note', ['last_edited'], unique=False)
    op.create_index(op.f('ix_note_note'), 'note', ['note'], unique=False)
    op.create_index(op.f('ix_note_note_date'), 'note', ['note_date'], unique=False)
    op.create_index(op.f('ix_note_title'), 'note', ['title'], unique=False)
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('reminder', sa.String(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('already_reminded', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_already_reminded'), 'reminder', ['already_reminded'], unique=False)
    op.create_index(op.f('ix_reminder_creation_date'), 'reminder', ['creation_date'], unique=False)
    op.create_index(op.f('ix_reminder_reminder'), 'reminder', ['reminder'], unique=False)
    op.create_index(op.f('ix_reminder_reminder_date'), 'reminder', ['reminder_date'], unique=False)
    op.create_index(op.f('ix_reminder_title'), 'reminder', ['title'], unique=False)
    op.create_table('note__tags',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note__tags')
    op.drop_index(op.f('ix_reminder_title'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_reminder_date'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_reminder'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_creation_date'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_already_reminded'), table_name='reminder')
    op.drop_table('reminder')
    op.drop_index(op.f('ix_note_title'), table_name='note')
    op.drop_index(op.f('ix_note_note_date'), table_name='note')
    op.drop_index(op.f('ix_note_note'), table_name='note')
    op.drop_index(op.f('ix_note_last_edited'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_creation_date'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_tag'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
