"""users table

Revision ID: c1a2f6174b5a
Revises: 24a0b10ebb92
Create Date: 2019-11-08 21:16:19.654989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a2f6174b5a'
down_revision = '24a0b10ebb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'user_id')
    # ### end Alembic commands ###
