"""empty message

Revision ID: fc198dd9d725
Revises: 16accaa63a27
Create Date: 2019-11-08 22:07:16.052481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc198dd9d725'
down_revision = '16accaa63a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('user_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
